import { Inter } from "next/font/google";
import "./globals.css";
// import { Toaster} from "react-hot-toast";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" data-theme="cupcake" className="scroll-smooth">
      <body className={inter.className}>
      
        <Toaster/>
     
      
      {children}</body>
    </html>
  );
}
